root: true
extends: ['@typescord', prettier]
plugins: [prettier]
parserOptions:
  project: tsconfig.json
rules:
  prettier/prettier: error
  import/namespace: off
  unicorn/prefer-node-protocol: off
  unicorn/prefer-module: off
env:
  node: true
  es2020: true
  jest: true
