name: Build
on:
  push:
    branches: [main]
    paths-ignore: ['*.{md,txt}', LICENSE, .*config, .vscode]
    tags-ignore: ['*']
  pull_request:
    branches: ['*']
    paths-ignore: ['*.{md,txt}', LICENSE, .*config, .vscode]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-latest, windows-2016, windows-latest, macos-latest]
        node: [15, 16]

    steps:
      - name: Force Git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Node.js v${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install --immutable
        env:
          npm_config_build_from_source: true

      - name: Package build
        run: yarn build

      - name: Build TypeScript files
        run: yarn build-ts --noEmit

      - name: Test
        run: yarn test

      - name: Lint
        run: yarn lint

  build_musl:
    name: Build (musl)
    runs-on: ubuntu-latest
    container:
      image: node:${{ matrix.node }}-alpine
    strategy:
      matrix:
        node: [15, 16]

    steps:
      - name: Setup environment
        run: |
          apk add --update
          apk add --no-cache ca-certificates git curl build-base python g++ make

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        run: yarn install --immutable
        env:
          npm_config_build_from_source: true
          npm_config_unsafe_perm: true

      - name: Package build
        run: yarn build

      - name: Build TypeScript files
        run: yarn build-ts --noEmit

      - name: Test
        run: yarn test

      - name: Lint
        run: yarn lint
