name: Prebuild
on:
  release:
    types: [published]

jobs:
  build:
    name: Prebuild
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Node v15
        uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: Install dependencies
        run: npx cross-env npm_config_build_from_source=true yarn install --immutable

      - name: Package prebuild
        run: yarn build

      - name: Upload prebuild asset
        uses: icrawl/action-artifact@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: 'build/stage/**/*.tar.gz'

  build_musl:
    name: Prebuild (musl)
    runs-on: ubuntu-latest
    container:
      image: node:15-alpine

    steps:
      - name: Setup env with Node v15
        run: |
          apk add --update
          apk add --no-cache ca-certificates git curl build-base python g++ make

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        run: npm_config_build_from_source=true yarn install --immutable

      - name: Package prebuild
        run: yarn build

      - name: Upload prebuild asset
        uses: icrawl/action-artifact@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: 'build/stage/**/*.tar.gz'
