name: Release Please
on:
  push:
    branches: [main]

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.release.outputs.release_created }}
      tag: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          default-branch: main
          pull-request-title-pattern: 'chore${scope}: release${component} v${version}'
          bump-minor-pre-major: true
          changelog-types: '[{"type":"feat","section":"Features"},{"type":"fix","section":"Bug Fixes"},{"type":"perf","section":"Performance Improvements"},{"type":"deps","section":"Dependencies"},{"type":"revert","section":"Reverts"},{"type":"docs","section":"Documentation"},{"type":"style","section":"Styles","hidden":true},{"type":"chore","section":"Miscellaneous Chores","hidden":true},{"type":"refactor","section":"Code Refactoring","hidden":true},{"type":"test","section":"Tests","hidden":true},{"type":"ci","section":"Continuous Integration","hidden":true}]'

  prebuild:
    name: Prebuild
    needs: release-please
    if: ${{ needs.release-please.outputs.released }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [15, 16]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Node.js v${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install --immutable
        env:
          npm_config_build_from_source: true

      - name: Package prebuild
        run: yarn build

      - name: Upload prebuild assets
        uses: svenstaro/upload-release-action@v2
        with:
          file: build/stage/**/*.tar.gz
          file_glob: true
          tag: ${{ needs.release-please.outputs.tag }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  prebuild_musl:
    name: Prebuild (musl)
    needs: release-please
    if: ${{ needs.release-please.outputs.released }}
    runs-on: ubuntu-latest
    container:
      image: node:${{ matrix.node }}-alpine
    strategy:
      matrix:
        node: [15] # TODO: add 16 when node:16-alpine is available

    steps:
      - name: Setup environment
        run: |
          apk add --update
          apk add --no-cache ca-certificates git curl build-base python g++ make

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        run: yarn install --immutable
        env:
          npm_config_build_from_source: true
          npm_config_unsafe_perm: true

      - name: Package prebuild
        run: yarn build

      - name: Upload prebuild assets
        uses: svenstaro/upload-release-action@v2
        with:
          file: build/stage/**/*.tar.gz
          file_glob: true
          tag: ${{ needs.release-please.outputs.tag }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.released }}
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js v15
        uses: actions/setup-node@v2
        with:
          node-version: 15
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: yarn install --immutable
        env:
          npm_config_build_from_source: true

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
